language: node_js
node_js:
  - iojs
  - "0.12"
  - "0.10"
  - "0.8"
env:
  - DEPLOY_VERSION=testing
services:
  - couchdb
before_install:
  - "npm config set spin false"
  - "npm install -g npm@~2"
  - "sudo mkdir -p /var/run/couchdb"
script: "npm run-script test-all"
